name: CI

on:
  push:
    branches: [ setup-task ]  # or 'main' or any branch you want
  pull_request:
    branches: [ setup-task ]

jobs:
  install-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # change this to match your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt